---

# -----------------------------------------------------------------------------
# download
# -----------------------------------------------------------------------------

- name: create download cache
  ansible.builtin.file:
    path: '{{ nvidia_driver_download_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: download NVIDIA driver
  ansible.builtin.get_url:
    url: '{{ nvidia_driver_url }}'
    dest: '{{ nvidia_driver_file }}'
    owner: root
    group: root
    mode: 0755

# -----------------------------------------------------------------------------
# install
# -----------------------------------------------------------------------------

- name: install build dependencies
  ansible.builtin.yum:
    name:
      - 'gcc'
      - 'kernel-devel-{{ ansible_kernel }}'
      - 'kernel-headers-{{ ansible_kernel }}'

- name: install driver
  ansible.builtin.command: ./{{ nvidia_driver_filename }} --silent
  args:
    chdir: '{{ nvidia_driver_download_dir }}'
  register: __nvidia_driver_installation
  changed_when: __nvidia_driver_installation.rc == 0
  failed_when: __nvidia_driver_installation.rc != 0

- name: remove gcc
  ansible.builtin.yum:
    name: gcc
    state: absent
  when: nvidia_driver_build_remove_gcc

...
