---

# -----------------------------------------------------------------------------
# download
# -----------------------------------------------------------------------------

- name: create download cache
  file:
    path: '{{ nvidia_driver_download_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: download NVIDIA driver
  get_url:
    url: '{{ nvidia_driver_url }}'
    dest: '{{ nvidia_driver_file }}'
    owner: root
    group: root
    mode: 0755

# -----------------------------------------------------------------------------
# install
# -----------------------------------------------------------------------------

- name: install build dependencies
  yum:
    name:
      - 'gcc'
      - 'kernel-devel-{{ ansible_kernel }}'
      - 'kernel-headers-{{ ansible_kernel }}'

- name: install driver
  command: ./{{ nvidia_driver_filename }} --silent
  args:
    chdir: '{{ nvidia_driver_download_dir }}'

- name: remove gcc
  yum:
    pkg: gcc
    state: absent
  when: nvidia_driver_build_remove_gcc

...
