---

- name: include main installation tasks
  ansible.builtin.include_tasks: nvidia-driver.yml
  when:
    - nvidia_driver_install

- name: include persistenced tasks
  ansible.builtin.include_tasks: persistenced.yml
  when:
    - nvidia_driver_persistenced

...
