---

- name: include driver type specific vars
  ansible.builtin.include_vars: '{{ nvidia_driver_type | lower }}.yml'

- name: blacklist nouveau kernel module
  community.general.kernel_blacklist:
    name: 'nouveau'

- name: unload nouveau kernel module
  community.general.modprobe:
    name: 'nouveau'
    state: absent

- name: check if nvidia driver is installed
  ansible.builtin.shell: |
    set -o pipefail
    nvidia-modprobe --version |
    grep -oP 'version \K[[:digit:]]+\.[[:digit:]]+'
  register: nvidia_driver_installed_version
  check_mode: no
  changed_when: >-
    nvidia_driver_installed_version.stdout != nvidia_driver_version
  failed_when: no

- name: check if nvidiactl device exists
  ansible.builtin.stat:
    path: '/dev/nvidiactl'
  register: nvidia_driver_nvidiactl
  check_mode: no
  changed_when: >-
    not nvidia_driver_nvidiactl.stat.exists
  failed_when: no

- name: check if nvidia driver kernel module exists for current kernel
  ansible.builtin.stat:
    path: '/lib/modules/{{ ansible_kernel }}/kernel/drivers/video/nvidia.ko'
  register: nvidia_driver_kernel_module
  check_mode: no
  changed_when: >-
    not nvidia_driver_kernel_module.stat.exists
  failed_when: no

- name: include actual installation
  ansible.builtin.include_tasks: install.yml
  when: >
    nvidia_driver_installed_version.changed or
    nvidia_driver_nvidiactl.changed or
    nvidia_driver_kernel_module.changed

- name: load nvidia kernel module
  community.general.modprobe:
    name: 'nvidia'
    params: 'NVreg_EnableMSI=0'
  register: nvidia_driver_module_loaded

- name: load nvidia unified virtual memory kernel module
  community.general.modprobe:
    name: 'nvidia_uvm'

- name: create nvidia devices
  ansible.builtin.script: 'nvidia-dev-create.sh'
  args:
    creates: /dev/nvidiactl

- name: check persistence mode
  ansible.builtin.command: 'nvidia-smi --query-gpu=persistence_mode --format=csv,noheader'
  register: persistence_mode
  check_mode: no
  changed_when: no

- name: keep nvidia devices ready-to-use
  ansible.builtin.command: nvidia-smi --persistence-mode=ENABLED
  when: persistence_mode.stdout.find('Enabled') == -1

...
